### ISSUE TITLE
Log merging errors

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/ocdsdata#1]
It would be nice to log the merging errors, to be able to identify issues in the data (or possibly in OCDS Merge).

My reading of the `compile_releases` function is that the errors are stored in the `_tmp_compiled_releases` table, which is both created and dropped in that function, so the errors are lost.

The `compile_releases` step's log does include warnings from ocdsmerge, so that's already useful.

**Comment by jpmckinney** [comment]
Similarly, the `error_data` column of the `_scrape_data` table is filled by the `scrape` function, but that table is dropped in the following `create_base_tables` function (since the DAG uses the default value `drop_scrape=True`).

It would be useful for `create_base_tables` to log the error data.

It's less useful for `scrape` to log the error data, because logs are truncated, and scrape logs are especially verbose. That said, if Scrapy's log level were configured to be `WARNING`, it could be done in the `scrape` function.

**Comment by kindly** [comment]
@jpmckinney thanks for the feedback! Sorry did not exepect anyone to see this repo yet so only just saw your messages now and for some reason I was not watching this repo.

> My reading of the `compile_releases` function is that the errors are stored in the `_tmp_compiled_releases` table, which is both created and dropped in that function, so the errors are lost.

The error form the compile step is copied the the non `tmp_` `compliled_releases` table here:
https://github.com/OpenDataServices/ocdsdata/blob/main/ocdsdata.py#L576

Nonetheless this is only can be seen in the postgres dump output which is not that useful to check anything has gone wrong.  
So there should at least print the errors and traceback in the airflow logs.   Idealy all output formats should have a marker against each compiled release to say there was a processing error in it.  More ideally there should be validation checks against each compiled release too, which could help explain the merge failures and other oddities.

> Similarly, the `error_data` column of the `_scrape_data` table is filled by the `scrape` function, but that table is dropped in the following `create_base_tables` function (since the DAG uses the default value `drop_scrape=True`).

Scrape logs mostly seem to be better in airflow, but decreacing verbosity could be good as I have to clean up logs due to taking too much disk space.  The default for the CLI tool is to keep the logs in db as all the tables are kept there.

> It would be useful for create_base_tables to log the error data.

Any stage after `compile_releases` is intended to be exception handling free, so it fails on all exceptions from then on.

**Comment by kindly** [comment]
Tracebacks are now reported in log files for compiled releases.
https://github.com/OpenDataServices/ocdsdata/blob/main/ocdsdata.py#L557

It would be good to capture them for the UI #3.
